### ISSUE TITLE
Improve the the way the project is documented

### ISSUE THREAD

**Issue by joebew42** [strattadb/margaret#227]
Hello here,

I would like to contribute to this project. So, I tried to follow the current documentation (various `.md` files in the project) but I was unable to run the application (e.g. if a database is required, or other setup information) or to run all the tests (what I see is that there are no tests at all, in the `api` project for example.)

Without tests it can be very difficult to change the code, maintain it or add a new feature.

So, in order to contribute I think it could be useful to put these information somewhere (maybe the main `README.md` can be the right place?).

I see that the project can use Docker. The way to use docker-compose or to use Docker in order to run the application can be documented, too. For example if a were a developer that wants to run the application locally, it could be very useful.

What do you think?

## Other nice-to-have improvements for the project

- Maybe a [Gitter](https://gitter.im) chat room can be useful to talk about the project
- Maybe a [TravisCI](https://travis-ci.org/) can be useful to setup a Continuous Integration process.

**Comment by strattadb** [comment]
Hi @joebew42,

You're right, currently there's no documentation. I'll try this week to document how to run the project locally and how the code is structured.

* I'll create the Gitter chat room today.
* Travis is already set up, although there are no tests yet, so it always passes.

Thanks!

**Comment by strattadb** [comment]
Here's the Gitter chat room https://gitter.im/margaretplatform/.
