### ISSUE TITLE
Automate Elixir dependency updates

### ISSUE THREAD

**Issue by greysteil** [strattadb/margaret#595]
Hey, I noticed you were using Renovate for automated JavaScript updates, and wondered if you'd be up for giving [Dependabot](https://dependabot.com) a go for automated Elixir dependency updates. I built it, and it's totally free for open source projects (and always will be) - I'm just trying to get more people using it. :octocat:

**Comment by dbstratta** [comment]
@greysteil Thanks! I'll look into it.
