### ISSUE TITLE
Logo design for margaret

### ISSUE THREAD

**Issue by reallinfo** [strattadb/margaret#666]
Hello! I am a graphic designer. I want to contribute to margaret. Do you want me to design a logo for the margaret? Actually, i have an idea. If you have an idea, you can say me.

**Comment by dbstratta** [comment]
@reallinfo Hi! That's great! Feel free to follow your idea, I don't have any currently.

Thank you so much for contributing to Margaret!

**Comment by reallinfo** [comment]
Sure! I degined a logo. What do you think?

![margaret](https://user-images.githubusercontent.com/36298335/41191885-94d8ab60-6bfe-11e8-9e13-afb664095a94.jpg)

**Comment by dbstratta** [comment]
I think it's wonderful! If you could send me the files I'll gladly start putting them in the application.

Thank you so much for your work!

**Comment by reallinfo** [comment]
You're welcome. I am glad you like it :) If you have another request, you can write me. 

I sent a pullrequest. Please checkt it.


https://github.com/strattadb/margaret/pull/687
